CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    restaurant_id VARCHAR(50) NOT NULL,
    restaurant_name VARCHAR(100) NOT NULL,
    order_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    delivery_city VARCHAR(50) NOT NULL,
    delivery_street VARCHAR(200),
    delivery_state VARCHAR(50),
    delivery_postal_code VARCHAR(20),
    delivery_country VARCHAR(50),
    delivery_latitude DOUBLE,
    delivery_longitude DOUBLE,
    restaurant_city VARCHAR(50) NOT NULL,
    restaurant_street VARCHAR(200),
    restaurant_state VARCHAR(50),
    restaurant_postal_code VARCHAR(20),
    restaurant_country VARCHAR(50),
    restaurant_latitude DOUBLE,
    restaurant_longitude DOUBLE,
    total_amount DECIMAL(10, 2),
    delivery_charge DECIMAL(10, 2),
    tax_amount DECIMAL(10, 2),
    grand_total DECIMAL(10, 2),
    delivery_partner_id BIGINT,
    estimated_delivery_minutes INTEGER,
    actual_delivery_minutes INTEGER,
    special_instructions VARCHAR(500),
    cancellation_reason VARCHAR(500),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    assigned_at TIMESTAMP,
    picked_at TIMESTAMP,
    delivered_at TIMESTAMP,
    cancelled_at TIMESTAMP
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id VARCHAR(50) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2),
    order_id BIGINT,
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE delivery_partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    current_city VARCHAR(50) NOT NULL,
    current_street VARCHAR(200),
    current_state VARCHAR(50),
    current_postal_code VARCHAR(20),
    current_country VARCHAR(50),
    current_latitude DOUBLE,
    current_longitude DOUBLE,
    vehicle_type VARCHAR(20),
    vehicle_number VARCHAR(20),
    assigned_order_count INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE idempotency_records (
    key_id VARCHAR(100) PRIMARY KEY,
    response_status INTEGER,
    response_body TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
