spring:
  application:
    name: OrderManagement
  profiles:
    active: dev
  
server:
  port: 8080

logging:
  level:
    com.example.ordermanagement: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html