spring:
  application:
    name: OrderManagement
  profiles:
    active: dev
  
server:
  port: 8080

logging:
  level:
    com.example.ordermanagement: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html